In [86]:

## Pandas Series: 


In [1]:
#!pip install nbconvert

In [2]:

import pandas as pd  
import numpy as np


In [2]:
# Version check:

print(pd.__version__)


1.4.4


In [3]:
# 1 D Array:
pd.array([1,2,3,4])


<IntegerArray>
[1, 2, 3, 4]
Length: 4, dtype: Int64

In [6]:
# Panda module Series:
ss = pd.Series([1,5, 2,3,4])


In [18]:
# convert a Panda module Series to Python list

print(list(ss))
print(ss.tolist())


[1, 5, 2, 3, 4]
[1, 5, 2, 3, 4]


In [19]:
# add, subtract, multiple and divide two Pandas Series

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])

print(s1+s2)
print(s1*s2)
print(s1/s2)


0     3
1     7
2    11
3    15
4    19
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [22]:
# compare the elements of the two Pandas Series

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print(s1 == s2)
print(s1 > s2)
print(s1 < s2)



0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [24]:
# convert a dictionary to a Pandas series

dict_a = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

print(pd.Series(dict_a))



a    100
b    200
c    300
d    400
e    800
dtype: int64


In [27]:
# convert a NumPy array to a Pandas series

npa = np.array([10, 20, 30, 40, 50])
print(npa)
print(pd.Series(npa))


[10 20 30 40 50]
0    10
1    20
2    30
3    40
4    50
dtype: int32


In [31]:
#***
#  change the data type of given a column or a Series

pds1 = pd.Series([100, 200, 'python', 300.12, 400])
print(pds1)
print(pd.to_numeric(pds1, errors="coerce"))


#** errors=
"""
If ‘raise’, then invalid parsing will raise an exception.
If ‘coerce’, then invalid parsing will be set as NaN.
If ‘ignore’, then invalid parsing will return the input.
""" 


0       100
1       200
2    python
3    300.12
4       400
dtype: object
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


'\nIf ‘raise’, then invalid parsing will raise an exception.\nIf ‘coerce’, then invalid parsing will be set as NaN.\nIf ‘ignore’, then invalid parsing will return the input.\n'

In [39]:
# convert the first column of a DataFrame as a Series

df1 = pd.DataFrame({'col1': [1, 2, 3, 4, 7, 11], 
                    'col2': [4, 5, 6, 9, 5, 0], 
                    'col3': [7, 5, 8,12, 1, 11]
                   })
print(df1)

pd_s1 = pd.Series(df1.col1)
#* OR: 
# s1 = df.ix[:,0]     # label-location based indexer 

print(pd_s1)


   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


In [47]:
#  convert a given Series to an array

pds3 = pd.Series([100, 200, 'python', 300.12, 400])

print(pds3)

print(list(pds3), type(list(pds3)))

#* To Numpy array:   
a = np.array(pds3.values.tolist())    #* the output has all "string" items.  
print(a) 


0       100
1       200
2    python
3    300.12
4       400
dtype: object
[100, 200, 'python', 300.12, 400] <class 'list'>
['100' '200' 'python' '300.12' '400']


In [57]:
#**
# convert Series of lists to one Series

pds4 = pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])

print(pds4)

print(pds4.explode())     #*  ".explode"
      
# Reset the index: 
print(pds4.explode().reset_index(drop=True))


0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
0       Red
0     Green
0     White
1       Red
1     Black
2    Yellow
dtype: object
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


In [64]:
# sort a given Series

pds5 = pd.Series(['100', '200', 'python', '300.12', '400'])

print(pds5)

print(pds5.sort_values())   #** 



0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object


In [67]:
# add some data to an existing Series 
new_pds5 = pds5.append(pd.Series(['500', 'php']))

print(new_pds5)


0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


In [68]:
# create a subset of a given series based on value and condition

s_6 = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(s_6)

s_6_new = s_6[s_6<6]   #** 
print(s_6_new)



0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [71]:
#**
# change the order of index of a given series
s_7 = pd.Series(data=[1, 2, 3, 4, 5], index=['a','b','c','d','e'])
print(s_7)

# REINDEX: 
s_7_new = s_7.reindex(['b', 'd', 'a', 'e', 'c'])    #** Reindex 
print(s_7_new)


a    1
b    2
c    3
d    4
e    5
dtype: int64
b    2
d    4
a    1
e    5
c    3
dtype: int64


In [76]:
#  mean and standard deviation of the data of a given Series
s_6 = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 3])

print(s_6.mean())
print(s_6.std())


4.5
2.8123105996832765


In [80]:
#* 
# get the items of a given series not present in another given series
sr1 = pd.Series([1, 2, 3,4, 5])
sr2 = pd.Series([2,4, 6, 8, 10])

print(sr1[sr1.isin(sr2)])  #** 
print(sr1[~sr1.isin(sr2)])  #** 


1    2
3    4
dtype: int64
0    1
2    3
4    5
dtype: int64


In [84]:
#***
# get the items which are not common of two given series:
sr1 = pd.Series([1, 2, 3,4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

# union:
union2 = pd.Series(np.union1d(sr1, sr2))
# intersection: 
interect2 = pd.Series(np.intersect1d(sr1, sr2))    
print(union2)
print(interect2)

print(union2[~union2.isin(interect2)])


0     1
1     2
2     3
3     4
4     5
5     6
6     8
7    10
dtype: int64
0    2
1    4
dtype: int64
0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64


In [89]:
# compute the minimum, 25th percentile, median, 75th, and maximum of a given serie 
s_6 = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 3])

print(s_6.median())
print(s_6.min())
print(s_6.max())

# PERCENTILES:    
res = np.percentile(s_6, q= [0, 25, 75, 100])
print(res)



4.5
0
9
[0.   2.75 6.25 9.  ]


In [95]:
# calculate the frequency counts of each unique value of a given series 
num_s = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))
#print(num_s)

print(num_s.value_counts())  #** 



7    8
2    5
5    5
6    5
8    4
9    3
1    3
4    3
3    2
0    2
dtype: int64


In [29]:
# display most frequent value in a given series and replace everything else as 'Other' in the series 

pds8 = pd.Series([3, 1, 1, 3, 2, 2, 1, 2, 3, 1, 2, 2, 2, 3, 3]) 

#**
np.random.RandomState(100)
num_series = pd.Series(np.random.randint(1, 5, [15]))

print(pds8.value_counts(), "\t", pds8.value_counts()[1], "\t", pds8.value_counts().index[:1])
#print(pds8)

# res = pds8[~ pds8.isin([pds8.value_counts()[1]])] = "other"    # doesn't work
res = pds8[~pds8.isin(pds8.value_counts().index[:1])] = "other"   #**

print(type(res), res)
print(type(pds8), "\n", pds8)


# result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
# print(num_series)


2    6
3    5
1    4
dtype: int64 	 4 	 Int64Index([2], dtype='int64')
<class 'str'> other
<class 'pandas.core.series.Series'> 
 0     other
1     other
2     other
3     other
4     other
5     other
6     other
7     other
8     other
9     other
10    other
11    other
12    other
13    other
14    other
dtype: object


In [36]:
# find the positions of numbers that are multiples of 5 of a given series:

pds9 = pd.Series(np.random.randint(2, 16, 10))

print(pds9) 

# take modulo of each element:
res = np.where(pds9 % 5 == 0)
print(res)



0     3
1     2
2    10
3     3
4     2
5    14
6    11
7     4
8     6
9     7
dtype: int32
(array([2], dtype=int64),)


In [4]:
# extract items at given positions of a given series

pds1 = pd.Series(np.random.randint(1, 18, 15))
print(pds1)

select_pos = [1, 5, 3, 6, 13]


res = pds1.take(select_pos)    #** 
print(res)



0      8
1      7
2      1
3     16
4     17
5      5
6     11
7     16
8     14
9      3
10     6
11     6
12     8
13     8
14     9
dtype: int32
1      7
5      5
3     16
6     11
13     8
dtype: int32


In [50]:
#**
# get the positions of items of a given series in another given series

pds2 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])   # pd.Series(np.random.randint(1, 35, 25))
print(pds2)
pds2_3 = pd.Series([1, 3, 5, 7, 10])  # pd.Series(np.random.randint(1, 34, 6))
pds2_3

#* Immutable sequence used for indexing and alignment. The basic object storing axis labels for all pandas objects.
res = [pd.Index(pds2).get_loc(elem) for elem in pds2_3]    #** 
print(res) 



0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
[0, 2, 4, 6, 9]


In [53]:
#**
# convert the first and last character of each word to upper case in each word of a given series 

pds3 = pd.Series(['php', 'python', 'java', 'c#'])
pds3

#*Map values of Series according to an input mapping or function. 
res = pds3.map(lambda x:x[0].upper() + x[1:-1] + x[-1].upper())   #**
print(res)




0       PhP
1    PythoN
2      JavA
3        C#
dtype: object


In [54]:
# calculate the number of characters in each word in a given series 

# result = series1.map(lambda x: len(x))
res = [len(item) for item in pds3]
print(res)



[3, 6, 4, 2]


In [63]:
#** 
# compute difference of differences between consecutive numbers of a given series

pds4 = pd.Series(np.random.randint(2, 20, 7))
print(pds4)

res = [pds4[i] - pds4[i+1] for i in range(len(pds4)-1)]
print(res)
#** First discrete difference of element. Calculates the difference of a Series element compared with another element
pds4.diff().diff()

# Alternate: 
# print(series1.diff().diff().tolist())



0    18
1    12
2    13
3     3
4    13
5     3
6    17
dtype: int32
[6, -1, 10, -10, 10, -14]


0     NaN
1     NaN
2     7.0
3   -11.0
4    20.0
5   -20.0
6    24.0
dtype: float64

In [7]:
#**
# convert a series of date strings to a timeseries

pds4 = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
pds4

res = pd.to_datetime(pds4)       #** datetime64[ns] 
print(res)



0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]


In [25]:
#** 
# get the day of month, day of year, week number and day of week from a given series of date strings

from dateutil.parser import parse

pds5 = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
pds5

#** both can work:
pds5 = pds5.map(lambda x: parse(x))    # OR
pds5 = pd.to_datetime(pds5) 

# Day of month:
print(pds5.dt.day.to_list())

# Day of year:
print(pds5.dt.month.to_list())

# Week number:
# pds5.dt.week.to_list()
print(pds5.dt.isocalendar().week.to_list())

# Day of week:
#print(pds5.dt.weekday.to_list())
print(pds5.dt.day_name().to_list())



[1, 2, 7, 6, 12, 6]
[1, 10, 3, 5, 4, 4]
[1, 39, 10, 19, 15, 14]
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


In [28]:
# convert year-month string to dates adding a specified day of the month

from dateutil.parser import parse

pds6 = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
pds6

print(pds6.map(lambda date: parse('10 ' + date)))



0   2015-01-10
1   2016-02-10
2   2017-03-10
3   2018-04-10
4   2019-05-10
dtype: datetime64[ns]


In [30]:
#***
# filter words from a given series that contain atleast two vowels 

from collections import Counter

pds7 = pd.Series(['Red', 'Pink', 'Green', 'Orange', 'Yellow', 'White'])
pds7

# color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)

#* Series.str.count(pat, flags=0)  - Count occurrences of pattern in each string of the Series/Index.
res = pds7[pds7.str.count('(!?)[aeiou]') >= 2]     #* REGEX

print(res)


#* REF: https://stackoverflow.com/questions/61593829/how-to-filter-words-that-contain-atleast-2-vowels-from-a-series 



2     Green
3    Orange
4    Yellow
5     White
dtype: object


In [32]:
# compute the Euclidean distance between two given series:  

pds8_1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
pds8_2 = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])

# Euclidean distance

# np.sqrt(np.sum([(a-b)*(a-b) for a, b in zip(x, y)])) 
res= np.linalg.norm(pds8_1 - pds8_2)

print(res)



16.492422502470642


In [40]:
# find the positions of the values neighboured by smaller values on both sides in a given series 

pds9 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1, 6, 8, 12, 14])
pds9

print(np.diff(pds9))
print(np.sign(np.diff(pds9)))

sign_diff = np.diff(np.sign(np.diff(pds9)))     #* '-2' here shows the hill here. 
print(sign_diff)   

# get the index: (index of zero values and add 2 to move them to correct position.)
minus_2_places = np.where(sign_diff == -2)[0]

print(minus_2_places + 1)  #* 1, -1 adds up and the -2 sits at one index previous. 



# REF: https://stackoverflow.com/questions/58703688/given-a-list-how-to-find-values-which-are-surrounded-by-smaller-values-on-both 



[ 7 -1 -2  1 -1 -2  1  3 -6  5  2  4  2]
[ 1 -1 -1  1 -1 -1  1  1 -1  1  1  1  1]
[-2  0  2 -2  0  2  0 -2  2  0  0  0]
[1 4 8]


In [57]:
# replace missing white spaces in a given string with the least frequent character

# addit as a list string
pds1 = pd.Series(list("abc def abcdef icd"))   #** 
pds1

# maybe drop the spaces before counting frequency....  
least_freq = pds1.value_counts().index[-1]
print(least_freq)

res = pds1.replace(' ', least_freq)
print("".join(pds1), '\n', "".join(res))



i
abc def abcdef icd 
 abcidefiabcdefiicd


In [64]:
#*
# compute the autocorrelations of a given numeric series 

pds2 = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
pds2
# random samples from a normal (Gaussian) distribution, with mean and std. given
np.random.normal(1, 10, 15)

# compute the lag-N autocorrelation - the Pearson correlation between the Series and its shifted self.  

autocorrelations = pds2.autocorr(lag=2)
print(autocorrelations)
autocorrelations = [pds2.autocorr(i).round(2) for i in range(11)]  #* whats going on here? 
print(autocorrelations)



0.018670427888799086
[1.0, 0.11, 0.02, -0.24, 0.16, 0.16, -0.24, -0.37, -0.52, 0.1, -0.04]


In [69]:
#  create a TimeSeries to display all the Sundays of given year 

pds3 = pd.Series(pd.date_range(start='1/1/2020', periods=52, freq='W-SUN'))
print(pds3)
pds3 = pd.Series(pd.date_range(start='01/01/2020', end='31/12/2020', periods=52))
print(pds3)



0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]
0    2020-01-01 00:00:00.000000000
1    2020-01-08 03:45:52.941176470
2    2020-01-15 07:31:45.882352941
3    2020-01-22 11:17:38.823529412
4    2

In [71]:
# convert given series into a dataframe with its index as another column on the dataframe.

pds4 = pd.Series(['a', 'b', 'c', 'd', 'e'])
pds4

df1 = pds4.to_frame().reset_index()   #*
print(df1) 

# REF: https://www.geeksforgeeks.org/convert-given-pandas-series-into-a-dataframe-with-its-index-as-another-column-on-the-dataframe/


   index  0
0      0  a
1      1  b
2      2  c
3      3  d
4      4  e


In [75]:
# stack two given series vertically and horizontally

pds5_1 = pd.Series([1,2,3,4,5,6,7,8,9,0])
pds5_1
pds5_2 = pd.Series(['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y'])
pds5_2

vertical = pds5_1.append(pds5_2)
vertical = pd.concat([pds5_1, pds5_2])

print(vertical)
horizontal = pd.concat([pds5_1, pds5_2], axis=1)
print(horizontal)



0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
9    0
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object
   0  1
0  1  p
1  2  q
2  3  r
3  4  s
4  5  t
5  6  u
6  7  v
7  8  w
8  9  x
9  0  y


C:\Users\Nitin Kumar\AppData\Local\Temp\ipykernel_29676\498835165.py:8: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  vertical = pds5_1.append(pds5_2)


In [78]:
# check the equality of two given series 

pds6_1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
pds6_2 = pd.Series([1, 8, 7, 5, 2, 5, 3, 9, 7, 1])

print(pds6_1 == pds6_2)



0     True
1     True
2     True
3     True
4    False
5     True
6     True
7    False
8     True
9     True
dtype: bool


In [82]:
# find the index of the first occurrence of the smallest and largest value of a given series 

pds7 = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])

print(pds7.idxmin())
print(pds7.idxmax())


9
4


In [85]:
# check "inequality" over the index axis of a given dataframe and a given series

df2 = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
print(df2)
pds8 = pd.Series([68, 75, 86, 80, None]) 


# When other is a Series, the columns of a DataFrame are aligned with the index of other and broadcast: 


print(df2.ne(pds8, axis=0))



      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83
       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True




### REFERENCE: https://www.w3resource.com/python-exercises/pandas/index-data-series.php 

    